site_name: Agent Fabric
site_url: https://iii-ei-stack.com/igp_manual/
theme:
  name: material
nav:
    - Home: index.md
    - 知識庫: kdb.md
    - 工作室: wks.md
    - 工作室接入: wks_integrate.md
    - 範例: examples.md

